//Variables that are set on-load
var monsterAbbreviation
var monsterHP;
var monsterMarginRight;
var monsterMarginTop;
var monsterWidth;
var monsterHeight;
var monsterHPbarsize;
var monsterHPbarDRAINAGE;
var monsterAccuracyLevel;
var monsterDefenceRank;
var monsterMax;
var monsterTime;
var monsterFirstHitTime;
var monsterKillPoint;
var monsterDeathTime;
var monsterBackground;
var playerMarginLeft;
var playerMarginTop;
var playerWidth;
var playerHeight;
var monsterHitsplatMarginLeft;
var monsterHitsplatMarginTop;
var monsterHPbarMarginLeft;
var monsterHPbarMarginTop;
var playerHitsplatMarginLeft;
var playerHitsplatMarginTop;
var playerHPbarMarginLeft;
var playerHPbarMarginTop;
var prayerOverheadMarginLeft;
var prayerOverheadMarginTop;
//Some of the other global variables
var hp2;
var jadhardmode;
function setmonster(monster) {
   jadhardmode = "Normal";
   document.getElementById("jadmode2").innerHTML=jadhardmode;
   switch(monster) {
   case "ogre": 
       monsterAbbreviation = "ogre";
	   monsterHP = 130; 
	   monsterMarginRight = "100px";
	   monsterMarginTop = "20px";
	   monsterWidth = "348px"
	   monsterHeight = "437px";
	   monsterHPbarsize = "30px";
	   monsterHPbarDRAINAGE = 0.230769;
	   monsterAccuracyLevel = 3;
	   monsterDefenceRank = 5;
	   monsterMax = 24;
	   monsterFirsthitTime = 2100;
	   monsterTime = 2100;
	   monsterKillPoint = 1;
	   monsterDeathTime = 7000;
	   monsterBackground = "url('images/bgogre.png')";
	   playerMarginLeft = "240px";
	   playerMarginTop = "230px";
	   playerWidth = "65px";
	   playerHeight = "140px";
	   monsterHitsplatMarginLeft = "182px";
       monsterHitsplatMarginTop = "155px";
       monsterHPbarMarginLeft = "180px";
       monsterHPbarMarginTop = "15px";
	   playerHitsplatMarginLeft = "9px";
       playerHitsplatMarginTop = "80px";
       playerHPbarMarginLeft = "5px";
       playerHPbarMarginTop = "40px";	 
       prayerOverheadMarginLeft = "8px";
       prayerOverheadMarginTop = "10px";		   
	   break;
   case "bird": 
       monsterAbbreviation = "bird";
	   monsterHP = 255; 
	   monsterMarginRight = "10px";
	   monsterMarginTop = "0px";
	   monsterWidth = "341px"
	   monsterHeight = "478px";
	   monsterHPbarsize = "30px";
	   monsterHPbarDRAINAGE = 0.117647058;
	   monsterAccuracyLevel = 3;
	   monsterDefenceRank = 5;
	   monsterMax = 23;
	   monsterFirsthitTime = 1000;
	   monsterTime = 2500;
	   monsterKillPoint = 1;
	   monsterDeathTime = 6000;
	   monsterBackground = "url('images/bgbird.png')";
	   playerMarginLeft = "240px";
	   playerMarginTop = "230px";
	   playerWidth = "65px";
	   playerHeight = "140px";
	   monsterHitsplatMarginLeft = "132px";
       monsterHitsplatMarginTop = "180px";
       monsterHPbarMarginLeft = "130px";
       monsterHPbarMarginTop = "100px";
	   playerHitsplatMarginLeft = "9px";
       playerHitsplatMarginTop = "80px";
       playerHPbarMarginLeft = "5px";
       playerHPbarMarginTop = "40px";	 
       prayerOverheadMarginLeft = "8px";
       prayerOverheadMarginTop = "10px";		   
	   break;	  
   case "imp": 
       monsterAbbreviation = "imp";
	   monsterHP = 500; 
	   monsterMarginRight = "203px";
	   monsterMarginTop = "155px";
	   monsterWidth = "64px"
	   monsterHeight = "68px";
	   monsterHPbarsize = "30px";
	   monsterHPbarDRAINAGE = 0.06;
	   monsterAccuracyLevel = 4;
	   monsterDefenceRank = 5;
	   monsterMax = 26;
	   monsterFirsthitTime = 1000;
	   monsterTime = 2080;
	   monsterKillPoint = 10;
	   monsterDeathTime = 4000;
	   monsterBackground = "url('images/bgimp.png')";
	   playerMarginLeft = "280px";
	   playerMarginTop = "120px";
	   playerWidth = "65px";
	   playerHeight = "140px";
	   monsterHitsplatMarginLeft = "2px";
       monsterHitsplatMarginTop = "10px";
       monsterHPbarMarginLeft = "0px";
       monsterHPbarMarginTop = "0px";
	   playerHitsplatMarginLeft = "9px";
       playerHitsplatMarginTop = "80px";
       playerHPbarMarginLeft = "5px";
       playerHPbarMarginTop = "40px";	  
       prayerOverheadMarginLeft = "8px";
       prayerOverheadMarginTop = "10px";		   
	   break;	
   case "jad": 
       monsterAbbreviation = "jad";
	   monsterHP = 250; 
	   monsterMarginRight = "-20px";
	   monsterMarginTop = "0px";
	   monsterWidth = "321px"
	   monsterHeight = "340px";
	   monsterHPbarsize = "30px";
	   monsterHPbarDRAINAGE = 0.12;
	   monsterAccuracyLevel = 100;
	   monsterDefenceRank = 2.3;
	   monsterMax = 97;
	   monsterFirsthitTime = 4800;
	   monsterTime = 4800;
	   monsterKillPoint = 100;
	   monsterDeathTime = 4000;
	   monsterBackground = "url('images/bgjad.png')";
	   playerMarginLeft = "387px";
	   playerMarginTop = "107px";
	   playerWidth = "45.5px";
	   playerHeight = "98px";
	   monsterHitsplatMarginLeft = "205px";
       monsterHitsplatMarginTop = "60px";
       monsterHPbarMarginLeft = "205px";
       monsterHPbarMarginTop = "0px";
	   playerHitsplatMarginLeft = "3px";
       playerHitsplatMarginTop = "55px";
       playerHPbarMarginLeft = "0px";
       playerHPbarMarginTop = "30px";
       prayerOverheadMarginLeft = "3px";
       prayerOverheadMarginTop = "2px";		   
	   break; 	   
   case "drag": 
       monsterAbbreviation = "drag";
	   monsterHP = 1200; 
	   monsterMarginRight = "195px";
	   monsterMarginTop = "100px";
	   monsterWidth = "148px"
	   monsterHeight = "152px";
	   monsterHPbarsize = "30px";
	   monsterHPbarDRAINAGE = 0.025;
	   monsterAccuracyLevel = 2.3;
	   monsterDefenceRank = 5;
	   monsterMax = 60;
	   monsterFirsthitTime = 1000;
	   monsterTime = 1800;
	   monsterKillPoint = 1000;
	   monsterDeathTime = 4200;
	   monsterBackground = "url('images/bgdrag.png')";
	   playerMarginLeft = "230px";
	   playerMarginTop = "160px";
	   playerWidth = "65px";
	   playerHeight = "140px";
	   monsterHitsplatMarginLeft = "55px";
       monsterHitsplatMarginTop = "60px";
       monsterHPbarMarginLeft = "55px";
       monsterHPbarMarginTop = "20px";
	   playerHitsplatMarginLeft = "9px";
       playerHitsplatMarginTop = "80px";
       playerHPbarMarginLeft = "5px";
       playerHPbarMarginTop = "40px";	  
       prayerOverheadMarginLeft = "8px";
       prayerOverheadMarginTop = "10px";			   
	   break; 	
   case "kk": 
       monsterAbbreviation = "kk";
	   monsterHP = 2600; 
	   monsterMarginRight = "150px";
	   monsterMarginTop = "50px";
	   monsterWidth = "311px"
	   monsterHeight = "324px";
	   monsterHPbarsize = "100px"; //was 200
	  // monsterHPbarsize = "200px"; //was 200
	   monsterHPbarDRAINAGE = 0.038461538; 
	   monsterAccuracyLevel = 4;
	   monsterDefenceRank = 5;
	   monsterMax = 30;
	   monsterFirsthitTime = 1700;
	   monsterTime = 1500;
	   monsterKillPoint = 100000;
	   monsterDeathTime = 8000;
	   monsterBackground = "url('images/bgkk.png')";
	   playerMarginLeft = "130px";
	   playerMarginTop = "220px";
	   playerWidth = "92px";
	   playerHeight = "200px";
	   monsterHitsplatMarginLeft = "140px";
       monsterHitsplatMarginTop = "140px";
       monsterHPbarMarginLeft = "106px"; //was 60
	   //monsterHPbarMarginLeft = "60px"; //was 60
       monsterHPbarMarginTop = "40px";	  
	   playerHitsplatMarginLeft = "15px";
       playerHitsplatMarginTop = "120px";
       playerHPbarMarginLeft = "13px";
       playerHPbarMarginTop = "62px";	 
       prayerOverheadMarginLeft = "16px";
       prayerOverheadMarginTop = "30px";		   
	   break;	   
   case "nope": 
       monsterAbbreviation = "nope";
	   monsterHP = 1000; 
	   monsterMarginRight = "0px";
	   monsterMarginTop = "0px";
	   monsterWidth = "592px"
	   monsterHeight = "552px";
	   monsterHPbarsize = "30px";
	   monsterHPbarDRAINAGE = 0.03;
	   monsterAccuracyLevel = 5;
	   monsterDefenceRank = 2.4;
	   monsterMax = 22;
	   monsterFirsthitTime = 2200; 
	   monsterTime = 2200;
	   monsterKillPoint = 10000000;
	   monsterDeathTime = 4000;
	   monsterBackground = "url('images/bgnope.png')";
	   playerMarginLeft = "250px";
	   playerMarginTop = "200px";
	   playerWidth = "65px";
	   playerHeight = "140px";
	   monsterHitsplatMarginLeft = "297px";
       monsterHitsplatMarginTop = "155px";
       monsterHPbarMarginLeft = "295px";
       monsterHPbarMarginTop = "75px";
	   playerHitsplatMarginLeft = "9px";
       playerHitsplatMarginTop = "80px";
       playerHPbarMarginLeft = "5px";
       playerHPbarMarginTop = "40px";	 
       prayerOverheadMarginLeft = "8px";
       prayerOverheadMarginTop = "10px";		   
	   break;	
   case "ele": 
       monsterAbbreviation = "ele";
	   monsterHP = 275; 
	   monsterMarginRight = "150px";
	   monsterMarginTop = "10px";
	   monsterWidth = "170px"
	   monsterHeight = "394px";
	   monsterHPbarsize = "30px";
	   monsterHPbarDRAINAGE = 0.109090909;
	   monsterAccuracyLevel = 3;
	   monsterDefenceRank = 2.6;
	   monsterMax = 40;
	   monsterFirsthitTime = 2700;
	   monsterTime = 2700;
	   monsterKillPoint = 0;
	   monsterDeathTime = 4000;
	   monsterBackground = "url('images/bgele.gif')";
	   playerMarginLeft = "270px";
	   playerMarginTop = "240px";
	   playerWidth = "65px";
	   playerHeight = "140px";
	   monsterHitsplatMarginLeft = "80px";
       monsterHitsplatMarginTop = "173px";
       monsterHPbarMarginLeft = "80px";
       monsterHPbarMarginTop = "30px";
	   playerHitsplatMarginLeft = "9px";
       playerHitsplatMarginTop = "80px";
       playerHPbarMarginLeft = "5px";
       playerHPbarMarginTop = "40px";	
       prayerOverheadMarginLeft = "8px";
       prayerOverheadMarginTop = "10px";		   
	   break;
   case "brid": 
       monsterAbbreviation = "brid";
	   monsterHP = 200; 
	   monsterMarginRight = "188px";
	   monsterMarginTop = "60px";
	   monsterWidth = "200px"
	   monsterHeight = "390px";
	   monsterHPbarsize = "30px";
	   monsterHPbarDRAINAGE = 0.15;
	   monsterAccuracyLevel = 10;
	   monsterDefenceRank = 3.5;
	   monsterMax = 25;
	   monsterFirsthitTime = 1800;
	   monsterTime = 1800;
	   monsterKillPoint = 0;
	   monsterDeathTime = 4000;
	   monsterBackground = "url('images/bgbrid.png')";
	   playerMarginLeft = "270px";
	   playerMarginTop = "130px";
	   playerWidth = "65px";
	   playerHeight = "140px";
	   monsterHitsplatMarginLeft = "144px";
       monsterHitsplatMarginTop = "53px";
       monsterHPbarMarginLeft = "140px";
       monsterHPbarMarginTop = "5px";
	   playerHitsplatMarginLeft = "9px";
       playerHitsplatMarginTop = "80px";
       playerHPbarMarginLeft = "5px";
       playerHPbarMarginTop = "40px";	
       prayerOverheadMarginLeft = "8px";
       prayerOverheadMarginTop = "10px";		   
	   break;	 
   case "me": 
       monsterAbbreviation = "me";
	   monsterHP = 99; 
	   monsterMarginRight = "254px";
	   monsterMarginTop = "145px";
	   monsterWidth = "92px"
	   monsterHeight = "64px";
	   monsterHPbarsize = "30px";
	   monsterHPbarDRAINAGE = 0.30303030303;
	   monsterAccuracyLevel = 2.5;
	   monsterDefenceRank = 2.5;
	   monsterMax = 50;
	   monsterFirsthitTime = 1000;
	   monsterTime = 3770;
	   monsterKillPoint = 0;
	   monsterDeathTime = 4000;
	   monsterBackground = "url('images/bgme.png')";
	   playerMarginLeft = "230px";
	   playerMarginTop = "130px";
	   playerWidth = "65px";
	   playerHeight = "140px";
	   monsterHitsplatMarginLeft = "43px";
       monsterHitsplatMarginTop = "23px";
       monsterHPbarMarginLeft = "40px";
       monsterHPbarMarginTop = "-15px";
	   playerHitsplatMarginLeft = "9px";
       playerHitsplatMarginTop = "80px";
       playerHPbarMarginLeft = "5px";
       playerHPbarMarginTop = "40px";	
       prayerOverheadMarginLeft = "8px";
       prayerOverheadMarginTop = "10px";		   
	   break;	   
   default: //Kalphite king (KK) is default
       monsterAbbreviation = "kk";
	   monsterHP = 2600; 
	   monsterMarginRight = "150px";
	   monsterMarginTop = "50px";
	   monsterWidth = "311px"
	   monsterHeight = "324px";
	   monsterHPbarsize = "100px";
	   monsterHPbarDRAINAGE = 0.038461538; 
	   monsterAccuracyLevel = 4;
	   monsterDefenceRank = 5;
	   monsterMax = 30;
	   monsterFirsthitTime = 1700;
	   monsterTime = 1500;
	   monsterKillPoint = 100000;
	   monsterDeathTime = 8000;
	   monsterBackground = "url('images/bgkk.png')";
	   playerMarginLeft = "130px";
	   playerMarginTop = "220px";
	   playerWidth = "92px";
	   playerHeight = "200px";
	   monsterHitsplatMarginLeft = "140px";
       monsterHitsplatMarginTop = "140px";
       monsterHPbarMarginLeft = "106px";
       monsterHPbarMarginTop = "40px";
	   playerHitsplatMarginLeft = "15px";
       playerHitsplatMarginTop = "120px";
       playerHPbarMarginLeft = "13px";
       playerHPbarMarginTop = "62px";	
       prayerOverheadMarginLeft = "8px";
       prayerOverheadMarginTop = "10px";		   
	   break;
   }
   hp2 = monsterHP; 
   if (monsterAbbreviation == "ele") {
		$("#player2div").css({"visibility": "hidden"});
		$("#player1div").css({"visibility": "hidden"});
		$("#game").css({"background-size": "629px 528px"});
   }
   else {
		$("#player2div").css({"visibility": "visible"});
		$("#player1div").css({"visibility": "visible"});
   }
   $("#greenhp2").css({"width": (hp2*monsterHPbarDRAINAGE)});
   $("#player2").attr("src", "gifs/" + monsterAbbreviation + "stand.gif");
   $("#player2div").css({"margin-right": monsterMarginRight});
   $("#player2div").css({'margin-top': monsterMarginTop});
   $("#player2").css({"width": monsterWidth});
   $("#player2").css({"height": monsterHeight});
   $("#greenhp2").css({"width": monsterHPbarsize});
   $("#hphp2").css({"width": monsterHPbarsize});
   $("#game").css('background-image', monsterBackground);
   $("#player1div").css({"margin-left": playerMarginLeft});
   $("#player1div").css({"margin-top": playerMarginTop});
   $("#player1").css({"width": playerWidth});
   $("#player1").css({"height": playerHeight});
   $("#player1frozen").css({"width": playerWidth});
   $("#player1frozen").css({"height": playerHeight});
   $("#hitsplat2").css({"margin-left": monsterHitsplatMarginLeft});
   $("#hitsplat2").css({"margin-top": monsterHitsplatMarginTop});
   $("#hphp2").css({"margin-left": monsterHPbarMarginLeft});
   $("#hphp2").css({"margin-top": monsterHPbarMarginTop});
   $("#hitsplat1").css({"margin-left": playerHitsplatMarginLeft});
   $("#hitsplat1").css({"margin-top": playerHitsplatMarginTop});
   $("#hphp1").css({"margin-left": playerHPbarMarginLeft});
   $("#hphp1").css({"margin-top": playerHPbarMarginTop});   
   $("#prayerOverheadDiv").css({"margin-left": prayerOverheadMarginLeft});
   $("#prayerOverheadDiv").css({"margin-top": prayerOverheadMarginTop});
   if (monster == "jad") $("#jadmode").css({"visibility": "visible"});
   else $("#jadmode").css({"visibility": "hidden"});
   $("audio").attr( "src", "audio/" + monsterAbbreviation + ".mp3" );
}